spring:
  application:
    name: antigravity-animal-system
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

animal:
  upload-path: d:/dn-project/uploads

resend:
  api-key: ${RESEND_API_KEY:}

jwt:
  secret: ${JWT_SECRET:secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey}
  expiration: 86400000 # 24 hours

logging:
  level:
    root: INFO
    com.dnproject.platform: DEBUG
